name: Deploy on gh-pages

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run docs

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          
      - run: npm run build
      - run: EOS_PRIVATE_KEY=${{ secrets.TEST_PRIVATEKEY_PIXEOS1GSWAP }} EOS_ACCOUNT_NAME=${{ secrets.TEST_ACCOUNTNAME_PIXEOS }} EOS_ACCOUNT_PERMISSION=${{ secrets.TEST_PERMISSION_PIXEOS }} EOS_PUBLIC_KEY=${{ secrets.TEST_PUBLICKEY_PIXEOS }} npm run test
          
      # - name: Publish to NPM
      - run: npm run publish:next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        
